# Define profiles here, which can be used by typing `/spin [profile_name]`
# A template below
#
# profile_name:
#   tracks:
#     track_name: track_weight
#     ...
#   cars:
#     car_name: car_weight
#     ...
default:
  tracks:
    - Charlotte Motor Speedway: 1
    - Lime Rock Park: 1
    - Okayama International Circuit: 1
    - Oran Park Raceway: 1
    - Oulton Park Circuit: 1
    - Rudskogen Motorsenter: 1
    - Summit Point Raceway: 1
    - Tsukuba Circuit: 1
    - Virginia International Raceway: 1
    - WeatherTech Raceway at Laguna Seca: 1
  cars:
    - Toyota GR86: 1
free:
  cars:
    - Cadillac CTS-V Racecar: 1
    - Formula Vee: 1
    - Global Mazda MX-5 Cup: 1
    - Kia Optima: 1
    - Lucas Oil Off Road Pro 2 Lite Truck: 1
    - Pontiac Solstice: 1
    - Radical SR8: 1
    - SCCA Spec Racer Ford: 1
    - Toyota GR86: 1
    - VW Beetle: 1
    - VW Jetta TDI Cup: 1
    - Legends: 1
    - Street Stock: 1
    - Legacy NASCAR Truck Chevrolet Silverado - 2008: 1
  tracks:
    - Charlotte Motor Speedway: 1
    - Concord Speedway: 1
    - Langley Speedway: 1
    - Lanier National Speedway: 1
    - Limaland Motorsports Park: 1
    - Lime Rock Park: 1
    - Okayama International Circuit: 1
    - Oran Park Raceway: 1
    - Oulton Park Circuit: 1
    - Oxford Plains Speedway: 1
    - Rudskogen Motorsenter: 1
    - South Boston Speedway: 1
    - Summit Point Raceway: 1
    - Thompson Speedway Motorsports Park: 1
    - Tsukuba Circuit: 1
    - USA International Speedway: 1
    - Virginia International Raceway: 1
    - WeatherTech Raceway at Laguna Seca: 1

layouts:
  YOU MUST PICK A TRACK AS WELL:
    - Asshole.: 1
  VIR:
    - Full: 1
    - South: 1
    - North: 1
    - Patriot: 1
    - Grand: 1
  Tsukuba:
    - 2k Full: 1
    - 2k Moto: 1
    - 2k Short: 1
  Summit:
    - Regular: 1
    - Short: 1
  Oulton:
    - Intl: 1
    - Fosters: 1
    - Island: 1
    - Intl no Hislop: 1
    - Intl no Brittens: 1
    - Intl no Chicanes: 1
    - Fosters w Hislop: 1
    - Historic: 1
  Oran:
    - GP: 1
    - South: 1
    - Moto: 1
  Okayama:
    - Full: 1
    - Short: 1
  Lime Rock:
    - GP: 1
    - Classic: 1
    - Chicanes: 1
    - West Bend: 1
  Charlotte:
    - Roval: 1
    - Roval 2018: 1
    - Roval Long 2018: 1
